// app/terms-of-service/page.tsx
import { Card, CardContent } from "@/components/ui/Card";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-amber-50 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Terms of Service
          </h1>
          <p className="text-xl text-gray-600">Effective Date: December 2024</p>
        </div>

        <Card>
          <CardContent className="pt-6">
            <div className="prose prose-lg max-w-none text-gray-700">
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  1. Acceptance of Terms
                </h2>
                <p className="mb-4">
                  By accessing or using Learnify (the Service), you agree to be
                  bound by these Terms of Service and our Privacy Policy. If you
                  disagree with any part of the terms, you may not access the
                  Service.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  2. Description of Service
                </h2>
                <p className="mb-4">
                  Learnify is an AI-powered educational platform that transforms
                  traditional PDF past questions into interactive quizzes and
                  learning experiences. The Service includes:
                </p>
                <ul className="list-disc pl-6 mb-4 space-y-2">
                  <li>AI-powered quiz generation from uploaded materials</li>
                  <li>Student practice and assessment tools</li>
                  <li>Teacher classroom management features</li>
                  <li>Institutional analytics and reporting</li>
                  <li>E-learning content curation</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  3. User Accounts
                </h2>
                <p className="mb-4">
                  <strong>3.1 Eligibility</strong>
                </p>
                <p className="mb-4">
                  You must be at least 13 years old to use the Service. Users
                  under 13 may only use the Service with parental consent and
                  through educational institution accounts.
                </p>

                <p className="mb-4">
                  <strong>3.2 Account Security</strong>
                </p>
                <p className="mb-4">
                  You are responsible for maintaining the confidentiality of
                  your account credentials and for all activities that occur
                  under your account. Notify us immediately of any unauthorized
                  use.
                </p>

                <p className="mb-4">
                  <strong>3.3 Account Types</strong>
                </p>
                <ul className="list-disc pl-6 mb-4 space-y-2">
                  <li>
                    <strong>Student Accounts:</strong> For individual learning
                    and practice
                  </li>
                  <li>
                    <strong>Teacher Accounts:</strong> For creating and managing
                    classroom content
                  </li>
                  <li>
                    <strong>Institutional Accounts:</strong> For campus-wide
                    deployment and administration
                  </li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  4. Content and Intellectual Property
                </h2>
                <p className="mb-4">
                  <strong>4.1 User Content</strong>
                </p>
                <p className="mb-4">
                  You retain ownership of any educational content you upload to
                  the Service. By uploading content, you grant Learnify a
                  license to process, store, and display that content for the
                  purpose of providing the Service.
                </p>

                <p className="mb-4">
                  <strong>4.2 AI-Generated Content</strong>
                </p>
                <p className="mb-4">
                  Quizzes and questions generated by our AI from your uploaded
                  materials are considered derivative works. You maintain rights
                  to the original content and receive a license to use the
                  AI-generated content.
                </p>

                <p className="mb-4">
                  <strong>4.3 Platform Intellectual Property</strong>
                </p>
                <p className="mb-4">
                  The Learnify platform, including its software, design,
                  trademarks, and proprietary algorithms, are owned by Learnify
                  and protected by intellectual property laws.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  5. Acceptable Use
                </h2>
                <p className="mb-4">You agree not to:</p>
                <ul className="list-disc pl-6 mb-4 space-y-2">
                  <li>
                    Upload content that infringes on intellectual property
                    rights
                  </li>
                  <li>
                    Use the Service for any illegal or unauthorized purpose
                  </li>
                  <li>Attempt to circumvent any security or access controls</li>
                  <li>Interfere with or disrupt the Service or servers</li>
                  <li>
                    Use the Service to create harmful or malicious content
                  </li>
                  <li>
                    Share account credentials or access with unauthorized users
                  </li>
                  <li>
                    Use automated systems to access the Service without
                    permission
                  </li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  6. Subscription and Payments
                </h2>
                <p className="mb-4">
                  <strong>6.1 Free Tier</strong>
                </p>
                <p className="mb-4">
                  The free tier provides limited access to basic features. We
                  reserve the right to modify free tier offerings at any time.
                </p>

                <p className="mb-4">
                  <strong>6.2 Paid Subscriptions</strong>
                </p>
                <p className="mb-4">
                  Paid subscriptions are billed in advance on a recurring basis.
                  You can cancel at any time, but no refunds are provided for
                  partial subscription periods.
                </p>

                <p className="mb-4">
                  <strong>6.3 Price Changes</strong>
                </p>
                <p className="mb-4">
                  We may change subscription prices with 30 days notice. Price
                  changes will not affect current subscription periods.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  7. Termination
                </h2>
                <p className="mb-4">
                  We may suspend or terminate your account if you violate these
                  Terms. Upon termination, your right to use the Service will
                  immediately cease. We may retain your data for a reasonable
                  period as required by law or for legitimate business purposes.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  8. Disclaimer of Warranties
                </h2>
                <p className="mb-4">
                  THE SERVICE IS PROVIDED AS IS WITHOUT WARRANTIES OF ANY KIND.
                  WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED,
                  SECURE, OR ERROR-FREE. AI-GENERATED CONTENT MAY CONTAIN
                  INACCURACIES AND SHOULD BE REVIEWED BY QUALIFIED EDUCATORS.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  9. Limitation of Liability
                </h2>
                <p className="mb-4">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, LEARNIFY SHALL NOT BE
                  LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
                  OR PUNITIVE DAMAGES RESULTING FROM YOUR USE OF THE SERVICE.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  10. Governing Law
                </h2>
                <p className="mb-4">
                  These Terms shall be governed by the laws of Ghana, without
                  regard to its conflict of law provisions. Any disputes shall
                  be resolved in the courts of Accra, Ghana.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  11. Changes to Terms
                </h2>
                <p className="mb-4">
                  We reserve the right to modify these Terms at any time. We
                  will provide notice of significant changes through the Service
                  or via email. Continued use after changes constitutes
                  acceptance of the modified Terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  12. Contact Information
                </h2>
                <p className="mb-4">
                  For questions about these Terms of Service, please contact us
                  at:
                </p>
                <div className="bg-gray-100 p-4 rounded-lg">
                  <p>
                    <strong>Email:</strong> legal@learnify.com
                  </p>
                  <p>
                    <strong>Address:</strong> Education Innovation Hub, Accra,
                    Ghana
                  </p>
                  <p>
                    <strong>Phone:</strong> +233 24 123 4567
                  </p>
                </div>
              </section>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
